### ISSUE TITLE
Reports?

### ISSUE THREAD

**Issue by JimLynchCodes** [webdemos/karma-cucumber-demo#1]
Wow, this is awesome!

I currently have karma set up with Istanbul code coverage tool. This is great as we like to see what % of our codebase is covered by unit tests. We are mostly using 'protractor-cucumber-framework' to run gherkin scenarios with ui / web tests in the step definitions. However, we would like to implement some of our step definitions as unit tests, and for that it's really awesome to have cucumber reports generated. 

It's awesome that your demo generates BOTH the cucumber reports and the code coverage reports. Can you explain what you mean by, "Jasmine style report" and "beautiful angular style report"? I can't find them anywhere in the project.

I'm also a little worried about having my code coverage dependant on step definitions. Do I need  to have any regular karma unit tests or can I all-out switch over to cucumber-karma tests? Nice demo though. I'm just trying to figure out the best way to fit it into our development process. 
Thanks,
Jim

**Comment by chendachao** [comment]
Thanks, @JimTheMan, I update the readme, please take a look at it.
